"""
Forensic Report PDF Generator — v2 (Court-Ready, 8-Section Format)
Generates a professional, court-admissible forensic certificate report with:
1. Case Information
2. Audio Metadata
3. Trust Score Summary
4. Layer-by-Layer Findings
5. Fraud Risk Analysis
6. Anomaly Timeline
7. Expert Interpretation
8. Final Verdict & Certification
"""

import io
import uuid
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable, PageBreak
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT


# ── Color palette ────────────────────────────────────────────────────────────
NAVY = colors.HexColor("#0a0f1e")
DARK_BLUE = colors.HexColor("#1e3a5f")
BLUE = colors.HexColor("#00d4ff")
GREEN = colors.HexColor("#00c96e")
AMBER = colors.HexColor("#fbbf24")
RED = colors.HexColor("#ef4444")
ORANGE = colors.HexColor("#f97316")
LIGHT_GRAY = colors.HexColor("#f1f5f9")
MID_GRAY = colors.HexColor("#64748b")
DARK_TEXT = colors.HexColor("#1e293b")
BORDER_COLOR = colors.HexColor("#cbd5e1")

MODEL_VERSION = "AudioNotary v2.0.0"


def _verdict_color(verdict: str):
    v = verdict.upper()
    if "AUTHENTIC" in v:
        return GREEN
    if "SUSPICIOUS" in v:
        return AMBER
    if "FRAUD" in v:
        return RED
    return RED


def _status_color(status: str):
    s = status.upper()
    if s == "PASS":
        return GREEN
    if s == "SUSPICIOUS":
        return AMBER
    return RED


def _threat_color(level: str):
    l = level.upper()
    if l == "CRITICAL":
        return RED
    if l == "HIGH":
        return ORANGE
    if l in ("MODERATE", "MEDIUM"):
        return AMBER
    return GREEN


def generate(analysis_result: dict) -> bytes:
    """
    Generate a court-ready PDF forensic report from the analysis result dict.
    Returns the PDF as bytes.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=2 * cm,
        leftMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
    )

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle("title", parent=styles["Normal"],
                                  fontSize=22, textColor=NAVY, spaceAfter=4,
                                  fontName="Helvetica-Bold", alignment=TA_CENTER)
    subtitle_style = ParagraphStyle("subtitle", parent=styles["Normal"],
                                    fontSize=10, textColor=MID_GRAY, spaceAfter=2,
                                    fontName="Helvetica", alignment=TA_CENTER)
    section_style = ParagraphStyle("section", parent=styles["Normal"],
                                   fontSize=13, textColor=NAVY, spaceBefore=16,
                                   spaceAfter=6, fontName="Helvetica-Bold")
    section_num_style = ParagraphStyle("sectionnum", parent=styles["Normal"],
                                       fontSize=13, textColor=BLUE, spaceBefore=16,
                                       spaceAfter=6, fontName="Helvetica-Bold")
    body_style = ParagraphStyle("body", parent=styles["Normal"],
                                fontSize=9, textColor=DARK_TEXT,
                                spaceAfter=4, fontName="Helvetica", leading=14)
    mono_style = ParagraphStyle("mono", parent=styles["Normal"],
                                fontSize=8, textColor=colors.HexColor("#374151"),
                                fontName="Courier", leading=12)
    small_gray = ParagraphStyle("smallgray", parent=styles["Normal"],
                                fontSize=8, textColor=MID_GRAY,
                                fontName="Helvetica")
    label_style = ParagraphStyle("label", parent=styles["Normal"],
                                 fontSize=8, textColor=MID_GRAY,
                                 fontName="Helvetica-Bold")

    elements = []

    # ══════════════════════════════════════════════════════════════════════════
    # HEADER
    # ══════════════════════════════════════════════════════════════════════════
    elements.append(Paragraph("AUDIONOTARY", title_style))
    elements.append(Paragraph("FORENSIC AUDIO ANALYSIS CERTIFICATE", subtitle_style))
    elements.append(Paragraph(f"Generated by {MODEL_VERSION}",
                               ParagraphStyle("ver", fontSize=7, textColor=MID_GRAY,
                                              fontName="Helvetica", alignment=TA_CENTER, spaceAfter=4)))
    elements.append(HRFlowable(width="100%", thickness=2, color=BLUE, spaceAfter=12))

    # Extract data
    case_id = str(uuid.uuid4()).upper()
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
    meta = analysis_result.get("file_metadata", {})
    verdict = analysis_result.get("verdict", "UNKNOWN")
    trust_score = analysis_result.get("trust_score", 0)
    layers = analysis_result.get("layers", [])
    fraud_summary = analysis_result.get("fraud_summary", {})

    # ══════════════════════════════════════════════════════════════════════════
    # SECTION 1: CASE INFORMATION
    # ══════════════════════════════════════════════════════════════════════════
    elements.append(Paragraph("1. CASE INFORMATION", section_style))

    case_data = [
        ["Case ID", case_id],
        ["Analysis Date", now],
        ["Analyzer Version", MODEL_VERSION],
        ["Analysis Type", f"{len(layers)}-Layer Forensic Audit"],
    ]

    case_table = Table(case_data, colWidths=[4 * cm, 13 * cm])
    case_table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME", (1, 0), (1, -1), "Courier"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("TEXTCOLOR", (0, 0), (0, -1), MID_GRAY),
        ("BACKGROUND", (0, 0), (-1, -1), LIGHT_GRAY),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.white, LIGHT_GRAY]),
        ("BOX", (0, 0), (-1, -1), 0.5, BORDER_COLOR),
        ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#e2e8f0")),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))
    elements.append(case_table)
    elements.append(Spacer(1, 12))

    # ══════════════════════════════════════════════════════════════════════════
    # SECTION 2: AUDIO METADATA
    # ══════════════════════════════════════════════════════════════════════════
    elements.append(Paragraph("2. AUDIO METADATA", section_style))

    meta_data = [
        ["File Name", meta.get("filename", "N/A")],
        ["File Size", f"{meta.get('file_size_bytes', 0):,} bytes"],
        ["Duration", f"{meta.get('duration_sec', 0):.3f} seconds"],
        ["Sample Rate", f"{meta.get('sample_rate', 0):,} Hz"],
        ["Format", meta.get("format", "N/A")],
        ["SHA-256 Hash", meta.get("file_hash", "N/A")],
    ]

    meta_table = Table(meta_data, colWidths=[4 * cm, 13 * cm])
    meta_table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME", (1, 0), (1, -1), "Courier"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("TEXTCOLOR", (0, 0), (0, -1), MID_GRAY),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.white, LIGHT_GRAY]),
        ("BOX", (0, 0), (-1, -1), 0.5, BORDER_COLOR),
        ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#e2e8f0")),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))
    elements.append(meta_table)
    elements.append(Spacer(1, 12))

    # ══════════════════════════════════════════════════════════════════════════
    # SECTION 3: TRUST SCORE SUMMARY
    # ══════════════════════════════════════════════════════════════════════════
    elements.append(Paragraph("3. TRUST SCORE SUMMARY", section_style))
    v_color = _verdict_color(verdict)

    verdict_data = [
        [
            Paragraph(f"<b>{verdict}</b>", ParagraphStyle(
                "v", fontSize=20, textColor=v_color,
                fontName="Helvetica-Bold", alignment=TA_CENTER
            )),
            Paragraph(f"<b>Trust Score</b><br/><font size=28 color='{v_color.hexval()}'>{trust_score}</font><font size=12>/100</font>",
                      ParagraphStyle("ts", fontName="Helvetica", alignment=TA_CENTER, leading=28))
        ]
    ]
    verdict_table = Table(verdict_data, colWidths=[9.5 * cm, 7.5 * cm])
    verdict_table.setStyle(TableStyle([
        ("BOX", (0, 0), (-1, -1), 2, v_color),
        ("LINEAFTER", (0, 0), (0, 0), 1, colors.HexColor("#e2e8f0")),
        ("TOPPADDING", (0, 0), (-1, -1), 14),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 14),
        ("LEFTPADDING", (0, 0), (-1, -1), 12),
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f8fafc")),
    ]))
    elements.append(verdict_table)
    elements.append(Spacer(1, 8))

    n_anomalies = sum(1 for l in layers if l.get("anomaly_detected"))
    n_layers = len(layers)
    n_pass = sum(1 for l in layers if l.get("status") == "PASS")
    n_fail = sum(1 for l in layers if l.get("status") == "FAIL")
    n_suspicious = sum(1 for l in layers if l.get("status") == "SUSPICIOUS")

    summary_text = (
        f"AudioNotary performed a <b>{n_layers}-layer forensic trust audit</b> on the submitted audio file. "
        f"<b>{n_anomalies} of {n_layers}</b> forensic layers reported anomalies. "
        f"Results: <font color='{GREEN.hexval()}'><b>{n_pass} PASS</b></font>, "
        f"<font color='{AMBER.hexval()}'><b>{n_suspicious} SUSPICIOUS</b></font>, "
        f"<font color='{RED.hexval()}'><b>{n_fail} FAIL</b></font>. "
        f"The overall Trust Score is <b>{trust_score}/100</b>, yielding a verdict of <b>{verdict}</b>."
    )
    elements.append(Paragraph(summary_text, body_style))
    elements.append(Spacer(1, 8))

    # Layer score summary table
    score_header = [["Layer", "Score", "Status"]]
    score_rows = []
    for layer in layers:
        s_color = _status_color(layer.get("status", "UNKNOWN"))
        score_rows.append([
            layer.get("layer", "Unknown"),
            f"{layer.get('score', 0)}/100",
            Paragraph(f"<b>{layer.get('status', 'N/A')}</b>",
                      ParagraphStyle("ss", fontSize=8, textColor=s_color, fontName="Helvetica-Bold")),
        ])
    score_data = score_header + score_rows
    score_table = Table(score_data, colWidths=[8 * cm, 3 * cm, 6 * cm])
    score_table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e2e8f0")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_GRAY]),
        ("BOX", (0, 0), (-1, -1), 0.5, BORDER_COLOR),
        ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#e2e8f0")),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))
    elements.append(score_table)
    elements.append(Spacer(1, 8))

    # ══════════════════════════════════════════════════════════════════════════
    # SECTION 4: LAYER-BY-LAYER FINDINGS
    # ══════════════════════════════════════════════════════════════════════════
    elements.append(Paragraph("4. LAYER-BY-LAYER FINDINGS", section_style))

    for idx, layer in enumerate(layers, 1):
        layer_name = layer.get("layer", "Unknown")
        layer_score = layer.get("score", 0)
        layer_status = layer.get("status", "UNKNOWN")
        s_color = _status_color(layer_status)

        layer_header = [
            [
                Paragraph(f"<b>Layer {idx}: {layer_name}</b>",
                           ParagraphStyle("lh", fontName="Helvetica-Bold", fontSize=10, textColor=NAVY)),
                Paragraph(f"Score: <b>{layer_score}/100</b>",
                           ParagraphStyle("ls", fontName="Helvetica", fontSize=9, alignment=TA_RIGHT)),
                Paragraph(f"<b>{layer_status}</b>",
                           ParagraphStyle("lst", fontName="Helvetica-Bold", fontSize=10,
                                          textColor=s_color, alignment=TA_RIGHT)),
            ]
        ]
        header_table = Table(layer_header, colWidths=[9 * cm, 4 * cm, 4 * cm])
        header_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), LIGHT_GRAY),
            ("BOX", (0, 0), (-1, -1), 1, s_color),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ]))
        elements.append(header_table)

        # Sub-metrics
        sub_data = [["Sub-Metric", "Score", "Finding"]]
        for metric_key, metric_val in layer.get("sub_metrics", {}).items():
            metric_name = metric_key.replace("_", " ").title()
            m_score = metric_val.get("score", "-")
            m_detail = str(metric_val.get("detail", ""))[:150]
            m_anomaly = metric_val.get("anomaly", False)
            if m_anomaly:
                m_detail = f"⚠ {m_detail}"
            sub_data.append([metric_name, str(m_score), m_detail])

        if len(sub_data) > 1:
            sub_table = Table(sub_data, colWidths=[4 * cm, 1.5 * cm, 11.5 * cm])
            sub_table.setStyle(TableStyle([
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 8),
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e2e8f0")),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
                ("BOX", (0, 0), (-1, -1), 0.5, BORDER_COLOR),
                ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#e2e8f0")),
                ("TOPPADDING", (0, 0), (-1, -1), 3),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ]))
            elements.append(sub_table)

        elements.append(Spacer(1, 10))

    # ══════════════════════════════════════════════════════════════════════════
    # SECTION 5: FRAUD RISK ANALYSIS
    # ══════════════════════════════════════════════════════════════════════════
    if fraud_summary:
        elements.append(Paragraph("5. FRAUD RISK ANALYSIS", section_style))

        threat_level = fraud_summary.get("threat_level", "UNKNOWN")
        t_color = _threat_color(threat_level)
        fraud_score = fraud_summary.get("fraud_intent_score", 0)

        fraud_data = [
            ["Threat Level", Paragraph(f"<b>{threat_level}</b>",
                                       ParagraphStyle("tl", fontSize=10, textColor=t_color, fontName="Helvetica-Bold"))],
            ["Fraud Intent Score", f"{fraud_score}/100"],
            ["Sensitive Data Requested", "YES" if fraud_summary.get("sensitive_data_requested") else "No"],
            ["Authority Impersonation", "YES" if fraud_summary.get("authority_impersonation") else "No"],
            ["Urgency Level", fraud_summary.get("urgency_level", "None")],
            ["Recommended Action", fraud_summary.get("recommended_action", "N/A")],
        ]

        fraud_table = Table(fraud_data, colWidths=[5 * cm, 12 * cm])
        fraud_table.setStyle(TableStyle([
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("TEXTCOLOR", (0, 0), (0, -1), MID_GRAY),
            ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.white, LIGHT_GRAY]),
            ("BOX", (0, 0), (-1, -1), 0.5, BORDER_COLOR),
            ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#e2e8f0")),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ]))
        elements.append(fraud_table)
        elements.append(Spacer(1, 6))

        # Plain english summary
        plain_summary = fraud_summary.get("plain_english_summary", "")
        if plain_summary:
            elements.append(Paragraph(f"<b>Analysis Summary:</b> {plain_summary}", body_style))

        # Flagged segments
        flagged = fraud_summary.get("flagged_segments", [])
        if flagged:
            elements.append(Spacer(1, 6))
            elements.append(Paragraph(f"<b>Flagged Segments ({len(flagged)}):</b>", body_style))
            flag_data = [["Severity", "Category", "Text", "Explanation"]]
            for seg in flagged[:10]:  # Limit to 10
                flag_data.append([
                    seg.get("severity", ""),
                    seg.get("category_label", ""),
                    f'"{seg.get("text", "")[:60]}"',
                    seg.get("explanation", "")[:80],
                ])
            flag_table = Table(flag_data, colWidths=[2 * cm, 3 * cm, 5 * cm, 7 * cm])
            flag_table.setStyle(TableStyle([
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 7),
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#fef2f2")),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#fff7ed")]),
                ("BOX", (0, 0), (-1, -1), 0.5, BORDER_COLOR),
                ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#e2e8f0")),
                ("TOPPADDING", (0, 0), (-1, -1), 3),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                ("LEFTPADDING", (0, 0), (-1, -1), 4),
            ]))
            elements.append(flag_table)

        elements.append(Spacer(1, 12))

    # ══════════════════════════════════════════════════════════════════════════
    # SECTION 6: ANOMALY TIMELINE
    # ══════════════════════════════════════════════════════════════════════════
    viz = analysis_result.get("visualization", {})
    anomaly_markers = viz.get("anomaly_markers", [])

    # Also check splice detection timestamps
    splice_layer = next((l for l in layers if "Cross-Modal" in l.get("layer", "")), None)
    splice_times = []
    if splice_layer:
        splice_times = (splice_layer.get("sub_metrics", {})
                        .get("splice_detection", {})
                        .get("splice_timestamps", []))

    if anomaly_markers or splice_times:
        section_num = "6" if fraud_summary else "5"
        elements.append(Paragraph(f"{section_num}. ANOMALY TIMELINE", section_style))

        tl_data = [["Timestamp", "Event", "Severity"]]
        for m in anomaly_markers:
            tl_data.append([
                f"{m.get('time_sec', 0):.2f}s",
                m.get("label", "Anomaly detected"),
                m.get("severity", "medium").upper(),
            ])
        for t in splice_times:
            tl_data.append([f"{t:.2f}s", "Spectral discontinuity — possible splice point", "HIGH"])

        tl_table = Table(tl_data, colWidths=[2.5 * cm, 11.5 * cm, 3 * cm])
        tl_table.setStyle(TableStyle([
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e2e8f0")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#fff7ed")]),
            ("TEXTCOLOR", (2, 1), (2, -1), RED),
            ("BOX", (0, 0), (-1, -1), 0.5, BORDER_COLOR),
            ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#e2e8f0")),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ]))
        elements.append(tl_table)
        elements.append(Spacer(1, 12))

    # ══════════════════════════════════════════════════════════════════════════
    # SECTION 7: EXPERT INTERPRETATION
    # ══════════════════════════════════════════════════════════════════════════
    section_num = "7" if (fraud_summary and (anomaly_markers or splice_times)) else "6" if (fraud_summary or anomaly_markers or splice_times) else "5"
    elements.append(Paragraph(f"{section_num}. EXPERT INTERPRETATION", section_style))

    # Generate interpretation based on results
    interp_parts = []
    if trust_score >= 75:
        interp_parts.append(
            "The audio exhibits characteristics consistent with authentic human speech. "
            "No significant indicators of synthetic generation, splicing, or manipulation were detected."
        )
    elif trust_score >= 50:
        interp_parts.append(
            "The audio presents some characteristics that warrant further investigation. "
            "While not conclusively identified as synthetic or manipulated, certain analysis layers "
            "have flagged potential anomalies."
        )
    else:
        interp_parts.append(
            "The audio exhibits significant indicators of potential manipulation, synthesis, "
            "or tampering. Multiple analysis layers have identified anomalies that are inconsistent "
            "with authentic, unaltered human speech recordings."
        )

    if n_fail > 0:
        failed_names = [l["layer"] for l in layers if l.get("status") == "FAIL"]
        interp_parts.append(
            f"The following layers reported FAIL status: {', '.join(failed_names)}. "
            "These findings suggest specific areas of concern that should be examined by a qualified "
            "forensic audio examiner."
        )

    if fraud_summary and fraud_summary.get("threat_level") in ("HIGH", "CRITICAL"):
        interp_parts.append(
            "IMPORTANT: The social engineering analysis has identified high-risk fraud indicators "
            "in the audio transcript. This includes patterns commonly associated with telephone fraud, "
            "phishing, or social engineering attacks. Immediate caution is advised."
        )

    for part in interp_parts:
        elements.append(Paragraph(part, body_style))
        elements.append(Spacer(1, 4))

    elements.append(Spacer(1, 8))

    # ══════════════════════════════════════════════════════════════════════════
    # SECTION 8: FINAL VERDICT & CERTIFICATION
    # ══════════════════════════════════════════════════════════════════════════
    next_num = int(section_num) + 1
    elements.append(Paragraph(f"{next_num}. FINAL VERDICT & CERTIFICATION", section_style))

    elements.append(HRFlowable(width="100%", thickness=1, color=BLUE, spaceAfter=8))

    cert_data = [
        ["Verdict", verdict],
        ["Trust Score", f"{trust_score}/100"],
        ["Layers Analyzed", str(n_layers)],
        ["Anomalies Detected", str(n_anomalies)],
        ["File SHA-256", meta.get("file_hash", "N/A")],
        ["Analysis Timestamp", now],
        ["Model Version", MODEL_VERSION],
    ]
    cert_table = Table(cert_data, colWidths=[4 * cm, 13 * cm])
    cert_table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME", (1, 0), (1, -1), "Courier"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("TEXTCOLOR", (0, 0), (0, -1), MID_GRAY),
        ("BOX", (0, 0), (-1, -1), 1, BLUE),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.HexColor("#f0f9ff"), colors.white]),
        ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#e2e8f0")),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))
    elements.append(cert_table)
    elements.append(Spacer(1, 12))

    cert_text = (
        f"<b>CERTIFICATION:</b> This forensic analysis was performed by <b>{MODEL_VERSION}</b> "
        f"on {now}. The SHA-256 integrity hash of the analyzed file has been recorded above. "
        f"Any alteration to the audio file subsequent to this analysis will produce a different hash "
        f"and invalidate this certificate. This report is generated for informational purposes. "
        f"For use as legal evidence, please consult a certified digital forensics professional."
    )
    elements.append(Paragraph(cert_text, small_gray))
    elements.append(Spacer(1, 4))
    elements.append(Paragraph(f"Case ID: {case_id} | {MODEL_VERSION} | Report generated {now}",
                               ParagraphStyle("footer", parent=styles["Normal"],
                                              fontSize=7, textColor=MID_GRAY,
                                              fontName="Helvetica", alignment=TA_CENTER)))

    doc.build(elements)
    return buffer.getvalue()